[package]
name = "wayback-rpki"
version = "0.0.1"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
default-run="wayback-rpki"

[[bin]]
name = "wayback-rpki"
path = "src/bin/updater.rs"


[dependencies]

regex="1"
reqwest = {version="0.11.9", features=["blocking"]}
anyhow = "1"

# json feature dependency
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}

tracing = "0.1"
tracing-subscriber = "0.3.3"

rayon = "1.5.1"

# database dependency
dotenv = "0.15.0"
diesel = {version= "2.0.3", features=["postgres", "r2d2", "chrono", "ipnetwork", "network-address", "numeric"]}

# api
actix-web = "4.3.1"
r2d2="0.8"

chrono = "0.4.19"
ipnetwork = "0.18.0"

structopt = "0.3"

indicatif = "0.17.3"
