[package]
name = "wayback-rpki"
version = "0.0.1"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"

[dependencies]

regex="1"
reqwest = {version="0.11.9", features=["blocking"]}

# json feature dependency
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}

tracing = "0.1"
tracing-subscriber = "0.3.3"

rayon = "1.5.1"
